### PR TITLE
[gonzalez-quint-coto] updated lexical model

### PR DESCRIPTION
**Pull request by victoriaq22**
updated lexical model for Cabecar keyboard, with new case sensitivity.

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by darcywong00** [comment]
Thank you for the update.
1. The lexical model version in source/gonzalez_quint_coto.cjp-latn.cabecar.model.kps needs to be updated from 1.0 to 1.1
2. The following files should be removed from the PR:
    * build/gonzalez_quint_coto.cjp-latn.cabecar.model.js 
    * 3 desktop.ini files (your project folder, source/, and build/ folders)

**Comment by victoriaq22** [comment]
Hi Darcy,

I believe I’ve made the correct changes now.  Thank you!

From: Darcy Wong ***@***.***>
Date: Monday, April 5, 2021 at 7:55 PM
To: keymanapp/lexical-models ***@***.***>
Cc: Victoria R. Quint ***@***.***>, Author ***@***.***>
Subject: Re: [keymanapp/lexical-models] [gonzalez-quint-coto] updated lexical model (#129)

Thank you for the update.

  1.  The lexical model version in source/gonzalez_quint_coto.cjp-latn.cabecar.model.kps needs to be updated from 1.0 to 1.1
  2.  The following files should be removed from the PR:
     *   build/gonzalez_quint_coto.cjp-latn.cabecar.model.js
     *   3 desktop.ini files (your project folder, source/, and build/ folders)

**Review by DavidLRowe — APPROVED** [review]

**Comment by DavidLRowe** [comment]
@victoriaq22 The changes to the files are fine, but your fork of the repository is out-of-date, resulting in merge conflicts. 

Are you using the GitHub method of submitting changes? (Now documented for keyboards at: https://help.keyman.com/developer/keyboards/github/) If so, the easiest thing to do is:
- make sure you have a copy of all your work in a safe place
- close this pull request
- delete your (outdated) fork of the repository
- follow the instructions to create a new fork
- submit your changed files to make a new pull request

Another possibility is for me to submit your changes. Let me know if you have any questions.

**Comment by victoriaq22** [comment]
Ok, I deleted the old repository and created a new fork, then a new pull request.  Please let me know if it’s all in the right place now!  Thank you!

From: DavidLRowe ***@***.***>
Date: Wednesday, April 7, 2021 at 6:09 PM
To: keymanapp/lexical-models ***@***.***>
Cc: Victoria R. Quint ***@***.***>, Mention ***@***.***>
Subject: Re: [keymanapp/lexical-models] [gonzalez-quint-coto] updated lexical model (#129)

@victoriaq22<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fvictoriaq22&data=04%7C01%7Cvictoria.r.quint.22%40dartmouth.edu%7C26bf1e8a51c742ed4c8808d8fa11c890%7C995b093648d640e5a31ebf689ec9446f%7C0%7C0%7C637534301576638187%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=aPC4rKrshm4wGZI551LABBxYFh9KMeqP92tWq2tVgQI%3D&reserved=0> The changes to the files are fine, but your fork of the repository is out-of-date, resulting in merge conflicts.

Are you using the GitHub method of submitting changes? (Now documented for keyboards at: https://help.keyman.com/developer/keyboards/github/<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fhelp.keyman.com%2Fdeveloper%2Fkeyboards%2Fgithub%2F&data=04%7C01%7Cvictoria.r.quint.22%40dartmouth.edu%7C26bf1e8a51c742ed4c8808d8fa11c890%7C995b093648d640e5a31ebf689ec9446f%7C0%7C0%7C637534301576648145%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=mp5VPcDROfo1LmcfOcFhpFzKJz5BQr%2BvwhlDOgXwipQ%3D&reserved=0>) If so, the easiest thing to do is:

  *   make sure you have a copy of all your work in a safe place
  *   close this pull request
  *   delete your (outdated) fork of the repository
  *   follow the instructions to create a new fork
  *   submit your changed files to make a new pull request

Another possibility is for me to submit your changes. Let me know if you have any questions.

**Pull request closed without merging**
