### PR TITLE
chmod a+x so it is  directly callable

### PR DESCRIPTION
**Pull request by rfaramir**
The only improvement left from  my #5

### CODE REVIEW

**Comment by mcdurdin** [comment]
You seem to have made this commit with the wrong username?

**Comment by rfaramir** [comment]
> You seem to have made this commit with the wrong username?

Hmmmm. I don't think so:
on mac Keyman work:
Randy-Dev-MacBook:mac rboring$ git log is_same_version.sh 
commit 0e0146f23a1bdf3344e9eb58c29bb6d2ff2e8f15
**Author: Randy Boring <randy_boring@sil.org>**
Date:   Tue Jan 22 11:58:12 2019 -0600

on lexical-model work:
Randy-Dev-MacBook:lexical-models rboring$ git log build.sh 
commit 4b6feb5eae4d41cbeb6fecfd0267de0c4be5061a (HEAD -> rb-build-chmod, origin/rb-build-chmod)
**Author: Randy Boring <randy_boring@sil.org>**
Date:   Sun Mar 17 23:52:23 2019 -0500

Team City output:
 Build stopped: This pull request is not from a repo maintainer and will not be automatically built (new); exit code 99 (Step: Don't allow autobuild of external repo owner PRs (Command Line)) (new)

My Author line is the same as before, so I suspect instead that I'm not a "repo maintainer" in this repo?

**Comment by mcdurdin** [comment]
You are a "repo maintainer" (aka on the Developer team). That commit 4b6feb5e is not showing any email address in GitHub - notice how it doesn't show your avatar?

**Comment by eddieantonio** [comment]
Hey @rfaramir! Please add <randy_boring@sil.org> to your GitHub list of emails. Instructions here: https://help.github.com/en/articles/adding-an-email-address-to-your-github-account

**Comment by mcdurdin** [comment]
Okay, sorry, found another place where we need to specify repo maintainers (in TeamCity configuration).

I am still puzzled as to why this commit (https://github.com/keymanapp/lexical-models/pull/6/commits/4b6feb5eae4d41cbeb6fecfd0267de0c4be5061a) didn't show your avatar but another commit you made (https://github.com/keymanapp/lexical-models/pull/5/commits/bd7b85a8650c61c40d31b3f3cec58859bcd1d79e) did. Was it what @eddieantonio said? Because as far as I could tell, the commits have the same email address associated with them.

**Comment by rfaramir** [comment]
Yes, that was  my exact puzzlement, too.

I've also added randy_boring@sil.org to my github account, though.

**Pull request merged**
