### PR TITLE
[katelem.ann-latn.getat] initial submission

### PR DESCRIPTION
**Pull request by DavidLRowe**
submission on behalf of author (replaces #107)

### CODE REVIEW

**Comment by DavidLRowe** [comment]
@darcywong00 You can see the initial work on PR #107. The only change I made was to add the casing information to the .ts file. Building the model does produce warnings about duplicate words, but my understanding is that is now permitted. Thanks!

**Comment by katelem247** [comment]
It's taking a long time

**Review by LornaSIL — APPROVED** [review]
LGTM

**Comment by DavidLRowe** [comment]
@katelem247 Thanks for your patience.

**Comment by katelem247** [comment]
Thanks everyone

**Pull request merged**
