### PR TITLE
[sil.lazz-latn.laz] change language tag and rename files

### PR DESCRIPTION
**Pull request by Nnyny**

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by Nnyny** [comment]
@DavidLRowe, could you help take a look at this?

**Comment by DavidLRowe** [comment]
Visual inspection looks fine and a local copy seems to compile, but the Team City build fails. @mcdurdin Any ideas?

**Comment by mcdurdin** [comment]
@DavidLRowe this looks like it might be a v17 regression. I opened https://github.com/keymanapp/keyman/issues/11503 to track this problem.

**Comment by mcdurdin** [comment]
Problem was resolved with #255. Should be all good now (this one and #254 both updated)

**Comment by Nnyny** [comment]
@DavidLRowe, please approve this. Thank you.

**Comment by DavidLRowe** [comment]
Approvals for keyboards and lexical models are paused for the moment because the builds system is being upgraded from Keyman v16 to v17. Apologies for the delay.

**Comment by Nnyny** [comment]
Thanks!

**Comment by Nnyny** [comment]
Hello @DavidLRowe, can I get your approval on this PR?

**Review by DavidLRowe — APPROVED** [review]
LGTM

**Pull request merged**
