### PR TITLE
himyarit_musnad.xsa.wordlist

### PR DESCRIPTION
**Pull request by RiyadhAlfareh**

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by dyacob** [comment]
Hello @DavidLRowe , @darcywong00 ,  and team, I'm checking in on behalf of @RiyadhAlfareh to see if there are any issues with the lexicon that he can address?  We can't view the TeamCity build so we're a bit in the dark.

I have updates to make for the Amharic and Tigrinya wordlists and have two more in the pipeline that I hope to get submitted this month, or early next.  If the certification procedure has any new steps since my last go-round I would be interested to know.  Thanks!

**Comment by DavidLRowe** [comment]
@RiyadhAlfareh Are you still working on this? It seems that there are a number of duplicated files. You may find it easier to get all the files in the proper folder structure on your local computer, then create a new pull request (and close this one rather than try to fix it up).

**Comment by RiyadhAlfareh** [comment]
I will close this and fix my files then create new pul

**Pull request closed without merging**
