### PR TITLE
[dotland.ru.russian] Reduced wordlist to 76 000 for faster loading.

### PR DESCRIPTION
**Pull request by dotland**
Reduced the wordlist from 250  000 to 76 000 for better performance.

Links: [https://github.com/dotland/lexical-model-ru](https://github.com/dotland/lexical-model-ru)

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by dotland** [comment]
Added language casing for capitalized text suggestions.

**Comment by DavidLRowe** [comment]
@dotland Let me know when you'd like a review.

**Comment by dotland** [comment]
Now all changes are final. This model has a much better performance and an almost comprehensive list of 76 000 words.

**Review by DavidLRowe — APPROVED** [review]

**Pull request merged**
