### PR TITLE
[aozcq] updated submission

### PR DESCRIPTION
**Pull request by victoriaq22**
fixed file names and updated version. please let me know if there are any issues remaining!  thanks!

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by DavidLRowe** [comment]
There are some extra files referenced and some ones that didn't get renamed. I thought I could delete the extra files in GitHub (I did that with one file), but it ends up it's more complicated than I realized. It's tricky to get all the references renamed. 

I'd be willing to take your files and submit a pull request. I think I'd start with Developer's Project, New Project, Wordlist Lexical Model and plug in information from your existing files, then copy the existing files into the right folders. But perhaps you'd like to try that yourself. Let me know what you think.

**Comment by victoriaq22** [comment]
Hi - I think it might be best if I send you the files.  I'm not quite sure where all the issues are.  Should I email the zipped file?  
Thank you!

**Comment by DavidLRowe** [comment]
Try emailing the zipped file. It's also possible to attach files here by dragging and dropping the file.

**Comment by victoriaq22** [comment]
I'm going to delete these files and close this pull request, then start a new one with the fixed files.  Thank you, David!

**Pull request closed without merging**
