### PR TITLE
fix: [nrc.en.mtnt] Replace left single quote with apostrophe

### PR DESCRIPTION
**Pull request by darcywong00**
Addresses the TODO of #143 in replacing the wordlist use of "left-single-quote" with "apostrophe".

However, this doesn't seem to improve the suggestions of contractions .

When I installed with Keyman for Android 16.0, typing "ill", "hes", etc didn't offer contractions as suggestions...

### CODE REVIEW

**Comment by darcywong00** [comment]
From standup meeting, we'll hold on this PR until @jahorton is able to implement the fix (https://github.com/keymanapp/lexical-models/issues/143#issuecomment-1096934795 ?) at a future sprint...

**Comment by jahorton** [comment]
Hmm.  Granted, all of the following tests were done on the Web-only test page, but...

image

But...

image

When extra-precise:

image

But being a little too close to 'j' with the first keystroke can prevent `he's` from showing as a suggestion - like, it wouldn't even be in the top 12.

image

vs

image

Still shows up.

**Comment by jahorton** [comment]
Granted, there _is_ the issue that we English speakers "expect" apostrophe omission (for contractions) to count as "less" of an error than forgetting a standard letter... but that's language-specific knowledge, and thus might be a bit harder to model properly.

**Comment by jahorton** [comment]
To be clear, this is using the build from https://github.com/keymanapp/keyman/pull/7612, which does not target this issue in any way.

**Comment by jahorton** [comment]
> From standup meeting, we'll hold on this PR until @jahorton is able to implement the fix ([#143 (comment)](https://github.com/keymanapp/lexical-models/issues/143#issuecomment-1096934795) ?) at a future sprint...

This tidbit is a separate issue.  That's worth addressing to be sure, but is not sufficient reason to hold back this PR.

**Review by jahorton — APPROVED** [review]

**Pull request merged**
