### PR TITLE
Initial submission of tbm.eo-shaw.esperanto_sxava

### PR DESCRIPTION
**Pull request by tomasbm01**

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by tomasbm01** [comment]
Thank you. I just fixed the `wordlist.tsv`  and  added a description.

**Comment by DavidLRowe** [comment]
The description change looks good as does the removal of the U+FEFF character. Unfortunately the tab character in the first line of wordlist.tsv has now been replaced by two spaces. I think that will prevent that word from being included. Can you replace those spaces with a tab?

**Comment by DavidLRowe** [comment]
Thanks!

**Pull request merged**
