### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by okandale**
Ready for review.

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. You'll see a "build failed" message until the Keyman team has reviewed the pull request and manually initiated the build process.

Every change committed to this branch will become part of this pull request. When you have finished submitting files and are ready for the Keyman team to review this pull request, please post a "Ready for review" comment.

**Comment by DavidLRowe** [comment]
Thanks for this submission. Sorry for the delay in review.

The version number needs to be changed in the .kps file (Keyman package source). It should be set to 1.2 (to match what you have in the HISTORY.md file. This is what a new build that gets offered to users.

I'd also suggest changing the "Laz Dictionary 1.2 generated from template." line in the .model.ts file to just "Laz Dictionary". It's just a comment, but if you include the version number then it needs to be updated (or risk confusing someone) for each new version.

**Review by okandale — COMMENTED** [review]
I believe I made the changes!

**Comment by DavidLRowe** [comment]
The .kps file still has:
`<Version URL="">1.1</Version>`

If you're using Keyman Developer, select the .kps file, Details tab, and update the version number:
image

**Comment by okandale** [comment]
I'm a little bit inexperienced when it comes to Github, so I'm not sure how to replace files! I just amended the code instead.

**Review by DavidLRowe — APPROVED** [review]

**Comment by DavidLRowe** [comment]
Thanks for persevering!

**Pull request merged**
