### PR TITLE
Cook islands maori

### PR DESCRIPTION
**Pull request by victoriaq22**
Here are the updated files that David helped with. Thanks!

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by darcywong00** [comment]
Is this a rename because #134 failed to deploy?

If so, akevai_oh_zhou_coto_quint folder can be removed.

**Review by DavidLRowe — APPROVED** [review]

**Comment by mcdurdin** [comment]
This failed to deploy with the following error:

```
Failed to locate /c/BuildAgent/work/e22cfa4d1a6faf97/models/release/akevai_oh_zhou_coto_quint/akevai_oh_zhou_coto_quint.rar-latn.cim/build/akevai_oh_zhou_coto_quint.rar-latn.cim.model_info
```

**Comment by DavidLRowe** [comment]
@darcywong00 see #139

**Comment by DavidLRowe** [comment]
@mcdurdin I'm mystified. I can't see where it's getting the reference to the old file (`akevai_oh_zhou_coto_quint.rar-latn.cim.model_info`).

**Comment by mcdurdin** [comment]
Looks like #139 fixes this. Good work!

**Pull request merged**
