### PR TITLE
cabecar updated wordlist

### PR DESCRIPTION
**Pull request by victoriaq22**
Wordlist updated by Rolando Coto, July 6 2020.  Fixes duplication of accents and nasality.

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by DavidLRowe** [comment]
@victoriaq22 Something went wrong with your addition of files.
- There's a commit with a message: "This commit does not belong to any branch on this repository." (If you click on "cabecar updated wordlist" above, you can see this.)
- For this pull request, which is working in the "cabecar2" branch of your fork of the lexical-models repository, "Files changed" is zero.

It's probably best to just close this pull request, delete the "cabecar2" branch and start again. (Don't worry! It's fine to delete unneeded branches.)

**Comment by DavidLRowe** [comment]
@victoriaq22 Well, it seems that this is a display problem with GitHub. If you haven't done anything yet, please hold off and I'll see if I can work with this PR as is. Thank!

**Comment by DavidLRowe** [comment]
Well, I downloaded the files from the cabecar2 branch and they end up being identical to what's already in the repository, so that would indicate that your changes didn't make it to the branch. 

So, I'm going to ask you to make a new branch (in your fork of the lexical-models repository), commit your files, then make a new pull request. 

I'll close this pull request, and you can delete your "cabecar2" branch.

**Pull request closed without merging**
