### PR TITLE
Obolo LM 1.1

### PR DESCRIPTION
**Pull request by katelem24**

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by DavidLRowe** [comment]
Now you need to add back in the changed files (wordlist, etc.).

**Comment by katelem24** [comment]
> Now you need to add back in the changed files (wordlist, etc.).

Done. Please cross-check.

**Comment by DavidLRowe** [comment]
The list of files in the package source (.kps) file includes ann_kb_48.ico which does not exist in this project. You either need to delete this name from the list of files, or else include it in the source folder (and change the location information in the list of files).

**Comment by katelem24** [comment]
Done

**Review by DavidLRowe — APPROVED** [review]

**Pull request merged**
