### PR TITLE
Himyarit musnad xsa sarb

### PR DESCRIPTION
**Pull request by RiyadhAlfareh**

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by DavidLRowe** [comment]
Thanks for working on a lexical model for this language and script. 

Unfortunately, some of the needed files are missing, and the files are not organised according to the needs of Keyman's automated build system. 

If you use Keyman Developer's New Project feature (Project menu, New Project menu item, "Wordlist Lexical Model"), the program will do the work of putting the files in the correct folders. You'll need to supply the three parts of the project name: author, BCP 47 code ("xsa") and model name. Suppose these are "himyarit_musnad", "xsa" and "wordlist". Then the model name would be "himyarit_musnad.xsa.wordlist" and that would be the name of the folder and the base name of many of the files. In addition, the project folder would be under a folder with just the author name, and that folder would be under the "release" (or "experimental") folder. So, with the example above you'd have: `release/himyarit_musnad/himyarit_musnad.xsa.wordlist` as the project folder.
In that folder you would have the following files:
```
HISTORY.md
LICENSE.md
README.md
himyarit_musnad.xsa.wordlist.kpj
himyarit_musnad.xsa.wordlist.model_info
```
along with a folder called `source`. In the `source` folder you would have:
```
himyarit_musnad.xsa.wordlist.kps
himyarit_musnad.xsa.wordlist.ts
readme.htm
welcome.htm
wordlist.tsv
```
where the `himyarit_musnad.xsa.wordlist.ts` file references the `wordlist.tsv` file.

In that wordlist.tsv file, you'll want to have each word in the wordlist on its own line. There's an option to include a tab and a numeric count after each word. That count will instruct the model as to the relative frequency of the words, so that Keyman will try to propose the most frequent words first. (If you omit the count, all the words will have priority.)

If you need more information, please write again.

**Comment by DavidLRowe** [comment]
You will likely find it easier to close this pull request and start another one (rather than try to fix this one up).

**Comment by RiyadhAlfareh** [comment]
Ok thanks

**Comment by RiyadhAlfareh** [comment]
Dear David
I followed your advice to build lexical himyarit Musnad xsa wordlist but
its look same wrongs please your support? Iam new with GitHub maybe i lost
some steps

في الثلاثاء، 7 مارس 2023 4:10 ص DavidLRowe ***@***.***> كتب:

**Comment by RiyadhAlfareh** [comment]
> Thanks for working on a lexical model for this language and script. 
> 
> Unfortunately, some of the needed files are missing, and the files are not organised according to the needs of Keyman's automated build system. 
> 
> If you use Keyman Developer's New Project feature (Project menu, New Project menu item, "Wordlist Lexical Model"), the program will do the work of putting the files in the correct folders. You'll need to supply the three parts of the project name: author, BCP 47 code ("xsa") and model name. Suppose these are "himyarit_musnad", "xsa" and "wordlist". Then the model name would be "himyarit_musnad.xsa.wordlist" and that would be the name of the folder and the base name of many of the files. In addition, the project folder would be under a folder with just the author name, and that folder would be under the "release" (or "experimental") folder. So, with the example above you'd have: `release/himyarit_musnad/himyarit_musnad.xsa.wordlist` as the project folder.
> In that folder you would have the following files:
> ```
> HISTORY.md
> LICENSE.md
> README.md
> himyarit_musnad.xsa.wordlist.kpj
> himyarit_musnad.xsa.wordlist.model_info
> ```
> along with a folder called `source`. In the `source` folder you would have:
> ```
> himyarit_musnad.xsa.wordlist.kps
> himyarit_musnad.xsa.wordlist.ts
> readme.htm
> welcome.htm
> wordlist.tsv
> ```
> where the `himyarit_musnad.xsa.wordlist.ts` file references the `wordlist.tsv` file.
> 
> In that wordlist.tsv file, you'll want to have each word in the wordlist on its own line. There's an option to include a tab and a numeric count after each word. That count will instruct the model as to the relative frequency of the words, so that Keyman will try to propose the most frequent words first. (If you omit the count, all the words will have priority.)
> 
> If you need more information, please write again.

Dear David
I followed your advice and send new issue please see what the wrong with

**Pull request closed without merging**
