### PR TITLE
Initial Upload of Mengisa Model for community feedback

### PR DESCRIPTION
**Pull request by MattGyverLee**

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by MattGyverLee** [comment]
I had some issues with Alpha versions, so I'm a bit late submitting this. I'd like to test this with community leaders tomorrow, so it can go in Experimental if it's not complete enough.

**Review by DavidLRowe — APPROVED** [review]

**Comment by DavidLRowe** [comment]
@MattGyverLee Hi, Matthew. It would be nice if you could replace the "generated from template" placeholders with actual descriptions that help the user decide whether to install this. Could be as simple as "predictive text for Mengisa" or the like.

**Comment by MattGyverLee** [comment]
Yeah, I'll clean it up for 1.0.1. i just needed something to show tomorrow.

**Pull request merged**
