### PR TITLE
added language code bal

### PR DESCRIPTION
**Pull request by rmlockwood**

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by DavidLRowe** [comment]
I see that your *.ts file is more complex than the default one, so perhaps issue https://github.com/keymanapp/lexical-models/issues/119 isn't relevant. (If that's the case, you can make a comment to that effect and close the issue.)

If the casing issue is relevant, would you want to include that change in this PR?

**Comment by rmlockwood** [comment]
Ok. I added the UseCasing.

**Review by DavidLRowe — APPROVED** [review]

**Comment by DavidLRowe** [comment]
fixes #119 
fixes #112

**Pull request merged**
