### PR TITLE
[nko] Initial creation

### PR DESCRIPTION
**Pull request by darcywong00**
Initial creation of N'Ko lexical model on behalf of a Keyman user.

`nko_wordlist.tsv` generated from PrimerPrep with 2 user-prodived N'Ko wordlists.

Will need a touch layout keyboard for N'Ko to test this. See keymanapp/keyboards#1294

### CODE REVIEW

**Comment by DavidLRowe** [comment]
When I sort the word list by word (rather than by frequency as it is in the file), the first three entries consist of combining diacritics: 

+ ‎07EC NKO COMBINING SHORT LOW TONE
+ 07EC ‎07F2 NKO COMBINING SHORT LOW TONE NKO COMBINING NASALIZATION MARK
+ 07F2 NKO COMBINING NASALIZATION MARK

It seems strange that these would be separate entries in the word list. (But then languages do a lot of strange things!)

The fourth entry in the sorted word list is: 
+ ‎064A ARABIC LETTER YEH

It seems very strange that this letter from another script shows up in the word list.

**Comment by darcywong00** [comment]
I'll email the author to confirm if he's ok with removing those items

**Comment by darcywong00** [comment]
I haven't heard back, but I went ahead and manually removed those 4 entries for now

**Comment by DavidLRowe** [comment]
@mcdurdin LGTM though it would be good if the author could review the source of those loose diacritics.

GH says I'm "not authorized to merge this pull request"

**Comment by mcdurdin** [comment]
> GH says I'm "not authorized to merge this pull request"

I've updated permissions so you should be able to merge future PRs 😄

**Pull request merged**
