### PR TITLE
New Burushaski Perso Arabic Lexical Model 

### PR DESCRIPTION
**Pull request by quwatsunny**
Hello Team, 

I had previously pull requested and received comments and guidance. After carefully following those lines, I am requesting again. Kindly cheque and let me know if any further changes needed. 

Best Regards,

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. You'll see a "build failed" message until the Keyman team has reviewed the pull request and manually initiated the build process.

Every change committed to this branch will become part of this pull request. When you have finished submitting files and are ready for the Keyman team to review this pull request, please post a "Ready for review" comment.

**Comment by DavidLRowe** [comment]
@quwatsunny Excellent. There's only one thing to change and that's a very recent development, or I would have mentioned it earlier. The .model_info file is no longer used (since all the information is now specified in the .kps file). Therefore, please delete the `burushos.bsk.burushaski.model_info` file. Thanks!

**Comment by quwatsunny** [comment]
> @quwatsunny Excellent. There's only one thing to change and that's a very recent development, or I would have mentioned it earlier. The .model_info file is no longer used (since all the information is now specified in the .kps file). Therefore, please delete the `burushos.bsk.burushaski.model_info` file. Thanks!

@DavidLRowe Thank you very much.  I have deleted the file now.

**Review by DavidLRowe — APPROVED** [review]

**Comment by DavidLRowe** [comment]
Thanks!

**Pull request merged**
