### PR TITLE
Teochew model

### PR DESCRIPTION
**Pull request by Cathaylaboratory**
I have change the name from teochow to teochew. I spelled the wrong name. I am sorry about that. The 035 tag is necessarry for showing it is the model for Teochew language, not hainam and Taiwanese. If I don't write this tag, this model will be confused with Taigi POJ model. Thanks.  Ready for review.

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. You'll see a "build failed" message until the Keyman team has reviewed the pull request and manually initiated the build process.

Every change committed to this branch will become part of this pull request. When you have finished submitting files and are ready for the Keyman team to review this pull request, please post a "Ready for review" comment.

**Comment by LornaSIL** [comment]
The keyboard tag is `nan-latn-035`.

**Comment by DavidLRowe** [comment]
The directory structure doesn't match what is needed by the repository. Your lexical model will not be found since it is in the wrong place. You have 
`release/cathaylab.nan-latn-035.teochew/`
but it needs to be 
`release/cathaylab/cathaylab.nan-latn-035.teochew/`

You'll need to delete the existing files and upload them to the proper place. (Or else close this pull request and submit another with the files in the proper place.)

**Comment by Cathaylaboratory** [comment]
Do you mean I need to set a new folder of cathaylab under the release, then I can put my model in the folder?

**Review by DavidLRowe — APPROVED** [review]

**Comment by DavidLRowe** [comment]
I needed to delete one file that remained in the wrong location, but otherwise it looks good.

**Comment by DavidLRowe** [comment]
@Cathaylaboratory Here's a late response to your question. If you have a keyboard active on your device which (for this case) supports "nan-Latn-035", you should be able to connect with the lexical model (also called a "dictionary") as discussed on this page: https://help.keyman.com/products/android/current-version/basic/installing-dictionaries

If you have further questions, you could ask in the [Keyman topic of the Language Software Community](https://community.software.sil.org/c/keyman/19)

**Pull request merged**
