### PR TITLE
GFF Tigrinya-Ethiopia Lexical Model v1.0

### PR DESCRIPTION
**Pull request by dyacob**
The lexical model is based on the content found from 100 issues of the Wegahta (ወጋሕታ) newspaper.  The wordlist better reflects the spelling conventions, and word choices, of Tigrinya as spoken in Eritrea as compared to the predecessor "GFF Tigrinya" lexical model which in turn is based on the UniLex project which makes no regional distinction.

### CODE REVIEW

**Comment by DavidLRowe** [comment]
Is "description" in .model_info correct? "Tigrinya Lexical Model derived from the UniLex word list for Tigrinya."

readme.htm also references Unilex. This differs from the description in README.md.

**Comment by dyacob** [comment]
@DavidLRowe -thanks for catching this! A fix has been applied.

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by DavidLRowe** [comment]
The readme.htm file still references Unilex, but you can change the next time you update the wordlist.

**Review by DavidLRowe — APPROVED** [review]

**Comment by DavidLRowe** [comment]
The build failed due to a typo in the filename. Since I was changing things, I copied the description from README.md to readme.htm.

**Pull request merged**
