### PR TITLE
Create English (Shavian alphabet) ReadLex lexical model

### PR DESCRIPTION
**Pull request by Shavian-info**

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by DavidLRowe** [comment]
In order to fit the naming convention (which keeps our automated build system happy), we need to have a consistent "author.en-shaw.readlex" name (used for the project name and the base name of many of the files in the project), where the "author" part is also used as the folder in which the project folder resides. So, for example, instead of 
```
shavian\en-shaw.readlex\shavian_info.en-shaw.readlex.kpj
```
we would need
```
shavian_info\shavian_info.en-shaw.readlex\shavian_info.en-shaw.readlex.kpj
```
and so on for all the files (assuming you choose `shavian_info` as the author name).

Sorry to be so picky, but it makes maintaining the build system easier. 

If it's too much trouble to rename the files in this pull request, please feel free to close this PR and open a new one.

Thanks for your contribution!

**Comment by Shavian-info** [comment]
I've tried to correct the folder names to match the required naming conventions.

**Comment by DavidLRowe** [comment]
@Shavian-info Looks good! The only question I have is about the source/english_shavian.jpg file. It is included in the package, but not specified as the image file (on the Details tab), so I don't think anything will use it. (Actually, I'm not sure I've seen any lexical model packages that have included a custom image, so I don't know whether that is currently implemented or not.)

I'd suggest that you either specify that .jpg file as the image file in the package source, or else remove the .jpg file from the source folder (and from the .kps package source).

Thanks!

**Comment by Shavian-info** [comment]
I've added in the reference to the Graphic File. Even if not currently supported, happy to keep it if it doesn't cause any issues.

**Review by DavidLRowe — APPROVED** [review]

**Pull request merged**
