### PR TITLE
gff.xan.gff_xamtanga v1.0

### PR DESCRIPTION
**Pull request by dyacob**
Introduction of a Xamtanga lexicon, extracted from a newspaper corpus.

This lexicon will pair with a new keyboard for Awngi & Xamtanga languages which will be submitted in the coming days. Perhaps I'm getting ahead of myself but thought to start the review process early for the lexicon.

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by DavidLRowe** [comment]
@dyacob Is this ready for review?

**Comment by dyacob** [comment]
@DavidLRowe , yes this and the Awngi one are ready to review.  With the caveat that the corresponding keyboard gets submitted this weekend -though they should work with the Mesobe Fidelat and Harege Fidelat keyboards which have the language tags.

**Comment by DavidLRowe** [comment]
You might want to take the copyright statement (or at least the year) out of readme.htm and welcome.htm. README.md doesn't need copyright or version number.

**Review by DavidLRowe — APPROVED** [review]

**Pull request merged**
