### PR TITLE
gff.byn.gff_blin v1.0.1

### LINKED ISSUE #203: bug(gff.byn.gff_blin): Blin Dictionary Downloads But Does Not Load
### Describe the bug

The new `gff.byn.gff_blin` lexicon does not get setup to work with the `gff_blin` keyboard.  The lexicon is discovered as an available dictionary, but after retrieval, does not appear as installed for the language and the words are not offered for selection.  The keyboard continues to work as if there is no connected dictionary.

### Reproduce the bug

1. Keyman > Installed languages > Bilin > Dictionary (Check for available dictionary)
2. The messages appear: "Checking for associated...." , "Downloading dictionary..." , "Dictionary download is finished" , "Resources successfully updated!"
3. The "Check for available dictionary" text remains, it is not replaced with the dictionary name.
4. Going into the Keyman app editor, or in local editors, and launching the Blin keyboard, the dictionary is not loaded, the top of the screen with the word options does not appear.
5. I've restarted Keyman, and restarted my phone, but no change. Other keyboards work fine.
6. Steps (1) and (2) are repeated, and the results are identical.

### Expected behavior

Following the "Resources successfully updated!" message, the Blin keyboard would begin to offer the terminology from the dictionary for selection.

### Related issues

_No response_

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

16.0.138

### Operating system

Android 13

### Device

Samsung S22

### Target application

Keyman App, any editor

### Browser

_No response_

### Keyboard name

gff_blin

### Keyboard version

1.5.1

### Language name

Blin

### Additional context

This issue could be related to BCP 47 code processing.  Both the keyboard and lexicon use language ID "byn-Ethi" , this is important because there is also a Latin convention for writing Blin endorsed by the Eritrean government (thus "byn-Latn" is possible).

The lexicon file name does _not_ include the `-Ethi` part, it is `gff.byn.gff_blin`.  Still, it is odd that the dictionary is located, and downloaded, it just does not get associated with the keyboard afterwards.

### PR DESCRIPTION
**Pull request by dyacob**
Fixes #203 .

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by dyacob** [comment]
@DavidLRowe & @darcywong00 , I just woke this morning and was happy to see the merger.  After merger, how long until the dictionary is deployed on a server for download by the Keyman app?  I just gave it a test now, including removal and reinstall of the gff_blin keyboard, and still encounter the problem described in #203.  Thanks!

**Comment by DavidLRowe** [comment]
Not sure. Usually within 24 hours, probably a lot less.

**Pull request merged**
