### PR TITLE
[sil.km.ggc] remove space after words

### PR DESCRIPTION
**Pull request by Nnyny**

### CODE REVIEW

**Comment by keyman-server** [comment]
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

**Comment by MakaraSok** [comment]
@jahorton could you please take a look at this? Thanks.

**Comment by MakaraSok** [comment]
The prediction does not work smoothly. At least to what I expect. The video below shows me trying to pick the first suggestion on the banner and press the top left key and repeat and the result is not always consistent.

https://github.com/keymanapp/lexical-models/assets/28331388/7c20ab59-2118-4c93-b401-1b58155a9460

**Comment by MakaraSok** [comment]
This is to clarify the behavior above. The TSEs and I have observed that the word prediction performs better after uninstalling one of the two leaving only one active, i.e. "Khmer Google Crawler".

This is before installing "Khmer Google Crawler". Things work smoothly as it could be.

https://github.com/keymanapp/lexical-models/assets/28331388/8088d05e-2bb0-47d4-bb11-2fde337bf0b0

This is after installing "Khmer Google Crawler" with CND still selected. Things work differently while performing the same test. The suggestion seems to be a little different even though the key presses are the same.

https://github.com/keymanapp/lexical-models/assets/28331388/53fcf1d9-1ab2-4a46-92b6-2f701cc16e0a

The prediction works smoothly without having CND in the mix.

https://github.com/keymanapp/lexical-models/assets/28331388/f6990fea-dc75-4f8d-bda6-549f8bf0dbbf

These have been tested on Simulator running `Keyman 17.0.272 beta`.

More testings on actual devices (Android & iOS) are underway. We expect to see how the keyboard and gcc perform (1) before the update and (2) after the update in this PR #241.

**Comment by Nnyny** [comment]
I have tested the ggc with KM v17.0.273 beta on my Android phone and it's working smoothly. 
Before the change:

https://github.com/keymanapp/lexical-models/assets/123520338/64ca5648-13cc-4c8e-892f-8d9887b84cbf

After the update:

https://github.com/keymanapp/lexical-models/assets/123520338/fe7747cc-5a8d-4716-a9c7-a26db64794b4

**Comment by Meng-Heng** [comment]
Here is the test result for `Keyman v-17.0.274 for iOS`. 
There are a few problems when using the `not` updated code. The issue is described in the video and matches the topic of this PR.

Before the code update:

https://github.com/keymanapp/lexical-models/assets/90595388/01e6cbd6-ab97-409e-9df8-57414bde3c96

After the code update:

https://github.com/keymanapp/lexical-models/assets/90595388/e584d825-8f3a-42c8-8dbd-4b53b59e09da

After implementing the code of this PR, everything is working normally.

**Comment by MakaraSok** [comment]
@bharanidharanj, could you try and test this using iOS simulator? You can use the latest beta with the current version of Khmer Angkor keyboard and the updated wordlist attached below.

[sil.km.ggc.model.kmp.zip](https://github.com/keymanapp/lexical-models/files/14382873/sil.km.ggc.model.kmp.zip)

**Comment by bharanidharanj** [comment]
Sure. I will do..

**Comment by bharanidharanj** [comment]
@MakaraSok Tested with the latest Keyman 17.0.274 build on iPhone 15 Pro Max / iOS 17.0 Simulator and here is my observation: 1. Installed the current version of Khmer Angkor Keyboard. 2. Downloaded and installed the (khmer_angkor) wordlist file. 3. Now, I have two dictionary files for the Khmer_Angkor keyboard. 4. Selected the updated dictionary file. 5. Opened the Keyman In-App. Switched to a Khmer Angkor keyboard. 6. Typed the text and verified that it removes the extra space (as shown on the video after.mp4). Seems to be working fine.

**Review by MakaraSok — COMMENTED** [review]
The tests have confirmed the the fix does work as expected on actual devices and as tested by BJ. 

For the next step, I would like to ask @jahorton to help and approve the changes in this PR.

**Review by jahorton — APPROVED** [review]

**Comment by mcdurdin** [comment]
Note: this did not bump the model version, so existing users would not have received an upgrade and the change may not be published.

**Comment by DavidLRowe** [comment]
@Nnyny Could you make a new pull request that updates the version number in the .kps file? It would be helpful also to update the README.md file with a short description of the changes. Thanks!

**Comment by mcdurdin** [comment]
> Could you make a new pull request that updates the version number in the .kps file? It would be helpful also to update the README.md file with a short description of the changes. Thanks!

@DavidLRowe @Nnyny I see #245 did this already. Sorry that I missed that before.

**Pull request merged**
