### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by rfaramir**
Just the basics to get going.

### CODE REVIEW

**Comment by darcywong00** [comment]
I had one in #3 that's already approved. Can you consolidate to that one?

**Comment by rfaramir** [comment]
Sure.

But I’m confused. It was approved but not merged? Because I did look for it
before writing it...

**Comment by eddieantonio** [comment]
I'm confused too... @jahorton, is there a reason #3 is delayed after being approved?

**Comment by rfaramir** [comment]
Yours is way better than mine. I’ll just delete my PR.  Then once yours is
in, I can update one small step missing in yours that mine had: chmod a+x.
Or is it easy to add that section to yours from here?

Or, even better, wouldn’t a chmod stick once  done and pushed,  so that
isn’t necessary in the README?

**Comment by rfaramir** [comment]
Darcy's README.md already in #3 is way better. Closing this one with prejudice.

**Comment by jahorton** [comment]
@jahorton Didn't realize I hadn't merged it... I guess I was waiting on an approval it already had.  Done.

**Pull request closed without merging**
