### PR TITLE
feat: add support for externally hosted models

### PR DESCRIPTION
**Pull request by mcdurdin**
See docs/externally-hosted-models.md for details

Related:
* [Design document](https://docs.google.com/document/d/1g2oR3xHMvJPIOKOI_gir-AjGd1LA2SiluPlS8EuFDNE/edit#)
* keymanapp/keyboards#1706

### CODE REVIEW

**Review by rc-swag — COMMENTED** [review]
Just the same comment on one #150.  Sure the scripts are creating `touch` the `source_is_binary` file and should also clean it up. Still think it could be mentioned in readme?

**Review by rc-swag — APPROVED** [review]
lgtm

**Comment by mcdurdin** [comment]
Note: I want to add a sha-256 hash for externally hosted files for reliability and safety, so moving this back to draft.

**Review by rc-swag — APPROVED** [review]
lgtm

**Pull request merged**
