### PR TITLE
teochow model submission

### PR DESCRIPTION
**Pull request by Cathaylaboratory**
here is my teochow model submission

### CODE REVIEW

**Comment by keyman-server** [comment]
Thank you for your pull request. You'll see a "build failed" message until the Keyman team has reviewed the pull request and manually initiated the build process.

Every change committed to this branch will become part of this pull request. When you have finished submitting files and are ready for the Keyman team to review this pull request, please post a "Ready for review" comment.

**Comment by DavidLRowe** [comment]
Thanks for your submission. 

I think that the project folder name can be just `cathaylab.nan-latn.teochow` (that is, without the `-035` in the language tag), unless there is a different orthography for that region. @mcdurdin Can you confirm?

(And what is region 035?) 

In order to fit in the structure of the repository your project folder (with name Author.LanguageTag.ModelName) needs to be under a folder with just the author name, so `cathaylab.nan-latn.teochow` would be the base folder for the project, and it would be in the folder `cathaylab`, which would in turn be under the `release` folder.

@mcdurdin Do we need to wait on new lexical models while you update the repository to use v17?

**Comment by Cathaylaboratory** [comment]
I think remain the 035 is important because Teochew is different with Taiwanese. 035 means southeast Asia.

**Comment by Cathaylaboratory** [comment]
I have change the name teochow to teochew to recorrect my false spelling. Have you received that?

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by mcdurdin** [comment]
> @mcdurdin Can you confirm?

I think that the region may be important in this case -- but then the keyboard will need to have that bcp47 listed in its registration also.

> @mcdurdin Do we need to wait on new lexical models while you update the repository to use v17?

No, the repository should be ready for new lexical models.

**Comment by Cathaylaboratory** [comment]
The nan-latn-tw is different with nan-latn-035, I choose 035 to represent teochew because many teochew users lives in Thai, Vietnam, and Canton. I consider there is southeast asia, this model will only match the teochew keyboard. I don't want this model to match nan-latn-tw.

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by mcdurdin** [comment]
It might be better for compatibility reasons to list each of the regions separately, nan-latn-th, nan-latn-vn etc., rather than using the numeric region code

**Pull request closed without merging**
