### PR TITLE
Fixes .kmp bundling.

### LINKED ISSUE #15: Package compilation improperly bundles resources
While the individual resources for each model are properly built at present, the .model.kmp package file itself is not.  The issue:  both welcome.htm and the *.js file with compiled model code within the .model.kmp are instead **_relative paths_** to the individual build products, rather than copies of the actual files themselves.

Upon trying to actually utilize the .kmps for development work in our apps, we get something like the following:

image

As you might imagine, this rapidly generates errors and results in an unusable model.

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #15.

The .kps entries for readme.htm were removed so that they didn't break .kmp compilation; the corresponding files do not yet exist in our examples.

### CODE REVIEW

**Comment by jahorton** [comment]
@mcdurdin That is true.  The compiler did not check to see if readme.htm actually existed - instead, it created its own (useless) readme.htm within the .kmp based only on the path string.

**Comment by mcdurdin** [comment]
So with this fix, I guess the build falls over if the file is missing?

**Comment by jahorton** [comment]
I figured that would be a standard solution; that's what builds usually do, right?  Why define it as part of the package if you're not defining it?

**Comment by mcdurdin** [comment]
Yes, that's what I want, just making sure :)

**Pull request merged**
